apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector: #selector는 이 리소스에게 제어되거나, 연결되어야 하는 다른 리소스를 식별
    app: second-app #app:second-app 레이블을 가진 모든 pod는 Service에 의해 제어됨
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    #- protocol: 'TCP'
    #  port: 443
    #  targetPort: 443
  type: LoadBalancer 